-- OroTitan Registry forward repair — bundle-wide persistence receipt closure.
-- Migration identity was generated by the governed Supabase CLI workflow.
-- Classification: PERSISTENCE / REGISTRY DATA-INTEGRITY DEFECT.
-- Analytical methodology change: NONE.
-- Historical Registry row mutation in migration: NONE.
-- Deployed V1.6 / V1.7 / V1.8 migration bytes are not rewritten.

begin;

do $$
begin
  if to_regprocedure('public.orotitan_validate_manifest_persistence_receipt(jsonb,jsonb)') is null
     or to_regprocedure('public.orotitan_register_manifest_bundle(uuid,text,jsonb,jsonb,jsonb,jsonb)') is null
     or to_regprocedure('public.orotitan_insert_event(uuid,text,text,text,text,text,jsonb)') is null
     or to_regprocedure('public.orotitan_existing_event(uuid,text,text)') is null
     or to_regclass('public.orotitan_run_events') is null then
    raise exception 'OroTitan Registry V1.8 primitives must exist before bundle persistence-integrity migration';
  end if;
end;
$$;

-- The storage attestation is a separate authority from the finalizer caller.
-- It is written only by the PostgreSQL management plane after an independent
-- private-GitHub reread and is immutable under the existing event guards.
alter table public.orotitan_run_events
  drop constraint orotitan_run_events_event_type_check;

alter table public.orotitan_run_events
  add constraint orotitan_run_events_event_type_check
  check (event_type = any (array[
    'RUN_CREATED'::text,
    'RUN_IDENTITY_BOUND'::text,
    'STAGE_STARTED'::text,
    'STAGE_CHECKPOINTED'::text,
    'STAGE_PAUSED'::text,
    'STAGE_RESUMED'::text,
    'BLOCKER_OPENED'::text,
    'BLOCKER_RESOLVED'::text,
    'STAGE_REOPENED'::text,
    'ARTIFACT_SET_SEALED'::text,
    'PERSISTENCE_ATTESTED'::text,
    'STAGE_FINALIZED'::text,
    'READY_TO_PUBLISH_DECLARED'::text,
    'PUBLISH_AUTHORIZED'::text,
    'PUBLISH_SUCCEEDED'::text,
    'PUBLISH_FAILED'::text,
    'RUN_CANCELLED'::text
  ]));

create or replace function public.orotitan_validate_attested_bundle_object(
  p_run_id uuid,
  p_stage_code text,
  p_artifact jsonb,
  p_expected_json jsonb default null
)
returns void
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_receipt jsonb := p_artifact->'persistence_receipt';
  v_attestation public.orotitan_run_events%rowtype;
  v_bytes bytea;
  v_text text;
  v_json jsonb;
  v_size bigint;
  v_sha256 text;
  v_git_blob_sha text;
  v_repository text := p_artifact->>'github_repository';
  v_path text := p_artifact->>'github_path';
  v_commit text := p_artifact->>'github_commit_sha';
  v_blob text := p_artifact->>'github_blob_sha';
  v_storage_uri text := p_artifact->>'storage_uri';
  v_artifact_id uuid;
  v_version integer;
  v_artifact_type text := p_artifact->>'artifact_type';
  v_event_id uuid;
  v_event_fingerprint text;
begin
  if coalesce(jsonb_typeof(p_artifact),'null') <> 'object' then
    raise exception 'BUNDLE_PERSISTENCE_RECEIPT_INVALID: registration must be object'
      using errcode = '22023';
  end if;

  begin
    v_artifact_id := (p_artifact->>'artifact_id')::uuid;
    v_version := (p_artifact->>'version')::integer;
  exception when others then
    raise exception 'BUNDLE_PERSISTENCE_RECEIPT_INVALID: invalid artifact_id/version'
      using errcode = '22023';
  end;

  if v_artifact_id is null or v_version is null or v_version < 1
     or v_artifact_type is null
     or p_artifact->>'media_type' is null
     or p_artifact->>'size_bytes' is null
     or p_artifact->>'content_sha256' is null then
    raise exception 'BUNDLE_PERSISTENCE_RECEIPT_INVALID: required artifact metadata missing'
      using errcode = '22023';
  end if;

  if p_artifact->>'storage_backend' is distinct from 'PRIVATE_GITHUB'
     or v_repository is distinct from 'robzer13/real-orotitan' then
    raise exception 'IMMUTABLE_LOCATOR_AUTHORITY_MISMATCH: canonical private GitHub repository required'
      using errcode = '23514';
  end if;

  if v_path is null or v_commit is null or v_blob is null or v_storage_uri is null
     or v_commit !~ '^[0-9a-f]{40}$'
     or v_blob !~ '^[0-9a-f]{40}$'
     or p_artifact->>'content_sha256' !~ '^[0-9a-f]{64}$' then
    raise exception 'BUNDLE_PERSISTENCE_RECEIPT_INVALID: immutable locator/hash malformed'
      using errcode = '22023';
  end if;

  if v_storage_uri is distinct from
     'github://' || v_repository || '@' || v_commit || '/' || v_path then
    raise exception 'BUNDLE_PERSISTENCE_RECEIPT_PROVENANCE_MISMATCH: storage_uri mismatch'
      using errcode = '23514';
  end if;

  if coalesce(jsonb_typeof(v_receipt),'null') <> 'object'
     or v_receipt->>'receipt_schema_version' is distinct from '1.1'
     or v_receipt->>'verification_method' is distinct from 'PRIVATE_GITHUB_ATTESTED_REREAD_EXACT_BYTES_V1'
     or v_receipt->>'storage_backend' is distinct from 'PRIVATE_GITHUB'
     or v_receipt->>'run_id' is null
     or v_receipt->>'stage_code' is null
     or v_receipt->>'artifact_id' is null
     or v_receipt->>'version' is null
     or v_receipt->>'artifact_type' is null
     or v_receipt->>'github_repository' is null
     or v_receipt->>'github_path' is null
     or v_receipt->>'github_commit_sha' is null
     or v_receipt->>'github_blob_sha' is null
     or v_receipt->>'attestation_event_id' is null
     or v_receipt->>'verified_content_base64' is null
     or v_receipt->>'verified_at' is null
     or coalesce((v_receipt->>'commit_path_resolved')::boolean,false) is not true then
    raise exception 'BUNDLE_PERSISTENCE_RECEIPT_MISSING_OR_INCOMPLETE'
      using errcode = '23514';
  end if;

  if (v_receipt->>'run_id')::uuid is distinct from p_run_id
     or v_receipt->>'stage_code' is distinct from p_stage_code
     or (v_receipt->>'artifact_id')::uuid is distinct from v_artifact_id
     or (v_receipt->>'version')::integer is distinct from v_version
     or v_receipt->>'artifact_type' is distinct from v_artifact_type
     or v_receipt->>'github_repository' is distinct from v_repository
     or v_receipt->>'github_path' is distinct from v_path
     or v_receipt->>'github_commit_sha' is distinct from v_commit
     or v_receipt->>'github_blob_sha' is distinct from v_blob then
    raise exception 'BUNDLE_PERSISTENCE_RECEIPT_IDENTITY_OR_PROVENANCE_MISMATCH'
      using errcode = '23514';
  end if;

  begin
    perform (v_receipt->>'verified_at')::timestamptz;
    v_event_id := (v_receipt->>'attestation_event_id')::uuid;
    v_bytes := decode(v_receipt->>'verified_content_base64','base64');
  exception when others then
    raise exception 'BUNDLE_PERSISTENCE_RECEIPT_INVALID: timestamp/event/base64 invalid'
      using errcode = '22023';
  end;

  v_size := octet_length(v_bytes);
  v_sha256 := encode(extensions.digest(v_bytes,'sha256'),'hex');
  v_git_blob_sha := encode(
    extensions.digest(
      convert_to('blob ' || v_size::text,'UTF8') || decode('00','hex') || v_bytes,
      'sha1'
    ),
    'hex'
  );

  if (p_artifact->>'size_bytes')::bigint is distinct from v_size then
    raise exception 'BUNDLE_VERIFIED_SIZE_MISMATCH' using errcode = '23514';
  end if;
  if p_artifact->>'content_sha256' is distinct from v_sha256 then
    raise exception 'BUNDLE_VERIFIED_SHA256_MISMATCH' using errcode = '23514';
  end if;
  if v_blob is distinct from v_git_blob_sha then
    raise exception 'BUNDLE_VERIFIED_GIT_BLOB_MISMATCH' using errcode = '23514';
  end if;

  begin
    v_text := convert_from(v_bytes,'UTF8');
  exception when others then
    raise exception 'BUNDLE_PERSISTENCE_RECEIPT_INVALID: bytes are not UTF-8'
      using errcode = '23514';
  end;

  if p_artifact->>'media_type' = 'application/json' then
    if not (p_artifact ? 'canonical_json_content') then
      raise exception 'BUNDLE_CANONICAL_JSON_CONTENT_MISSING'
        using errcode = '23514';
    end if;
    begin
      v_json := v_text::jsonb;
    exception when others then
      raise exception 'BUNDLE_PERSISTENCE_RECEIPT_INVALID: bytes are not valid JSON'
        using errcode = '23514';
    end;
    if v_json is distinct from p_artifact->'canonical_json_content' then
      raise exception 'BUNDLE_VERIFIED_BYTES_JSON_MISMATCH'
        using errcode = '23514';
    end if;
    if p_expected_json is not null
       and p_artifact->'canonical_json_content' is distinct from p_expected_json then
      raise exception 'BUNDLE_SUBMITTED_JSON_MISMATCH'
        using errcode = '23514';
    end if;
  elsif p_expected_json is not null then
    raise exception 'BUNDLE_EXPECTED_JSON_REQUIRES_APPLICATION_JSON'
      using errcode = '23514';
  end if;

  select * into v_attestation
  from public.orotitan_run_events
  where event_id = v_event_id;

  if not found
     or v_attestation.run_id is distinct from p_run_id
     or v_attestation.stage_code is distinct from p_stage_code
     or v_attestation.event_type is distinct from 'PERSISTENCE_ATTESTED'
     or v_attestation.actor_type is distinct from 'SYSTEM' then
    raise exception 'IMMUTABLE_LOCATOR_AUTHORITY_MISSING_OR_MISMATCHED'
      using errcode = '23514';
  end if;

  if v_attestation.payload->>'attestation_schema_version' is distinct from '1.0'
     or v_attestation.payload->>'verification_method' is distinct from 'GITHUB_CONNECTOR_PRIVATE_REREAD_V1'
     or v_attestation.payload->>'trust_boundary' is distinct from 'SUPABASE_MANAGEMENT_PLANE'
     or v_attestation.payload->>'storage_backend' is distinct from 'PRIVATE_GITHUB'
     or coalesce((v_attestation.payload->>'commit_path_resolved')::boolean,false) is not true
     or (v_attestation.payload->>'run_id')::uuid is distinct from p_run_id
     or v_attestation.payload->>'stage_code' is distinct from p_stage_code
     or (v_attestation.payload->>'artifact_id')::uuid is distinct from v_artifact_id
     or (v_attestation.payload->>'version')::integer is distinct from v_version
     or v_attestation.payload->>'artifact_type' is distinct from v_artifact_type
     or v_attestation.payload->>'github_repository' is distinct from v_repository
     or v_attestation.payload->>'github_path' is distinct from v_path
     or v_attestation.payload->>'github_commit_sha' is distinct from v_commit
     or v_attestation.payload->>'github_blob_sha' is distinct from v_blob
     or v_attestation.payload->>'storage_uri' is distinct from v_storage_uri
     or (v_attestation.payload->>'size_bytes')::bigint is distinct from v_size
     or v_attestation.payload->>'content_sha256' is distinct from v_sha256
     or (v_attestation.payload->>'verified_at')::timestamptz
          is distinct from (v_receipt->>'verified_at')::timestamptz then
    raise exception 'IMMUTABLE_LOCATOR_AUTHORITY_MISSING_OR_MISMATCHED'
      using errcode = '23514';
  end if;

  v_event_fingerprint := encode(
    extensions.digest(convert_to(v_attestation.payload::text,'UTF8'),'sha256'),
    'hex'
  );
  if v_attestation.request_fingerprint_sha256 is distinct from v_event_fingerprint then
    raise exception 'IMMUTABLE_LOCATOR_AUTHORITY_FINGERPRINT_MISMATCH'
      using errcode = '23514';
  end if;
end;
$$;

-- Management-plane helper for production attestations. The caller must have
-- independently reread the private GitHub object before invoking this helper.
create or replace function public.attest_orotitan_persistence_locator(
  p_run_id uuid,
  p_stage_code text,
  p_attestation_payload jsonb
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_event_id uuid;
  v_fingerprint text;
  v_idempotency_key text;
  v_retry jsonb;
begin
  if coalesce(jsonb_typeof(p_attestation_payload),'null') <> 'object'
     or p_attestation_payload->>'attestation_schema_version' is distinct from '1.0'
     or p_attestation_payload->>'verification_method' is distinct from 'GITHUB_CONNECTOR_PRIVATE_REREAD_V1'
     or p_attestation_payload->>'trust_boundary' is distinct from 'SUPABASE_MANAGEMENT_PLANE'
     or p_attestation_payload->>'storage_backend' is distinct from 'PRIVATE_GITHUB'
     or p_attestation_payload->>'github_repository' is distinct from 'robzer13/real-orotitan'
     or p_attestation_payload->>'github_commit_sha' !~ '^[0-9a-f]{40}$'
     or p_attestation_payload->>'github_blob_sha' !~ '^[0-9a-f]{40}$'
     or p_attestation_payload->>'content_sha256' !~ '^[0-9a-f]{64}$'
     or coalesce((p_attestation_payload->>'commit_path_resolved')::boolean,false) is not true
     or (p_attestation_payload->>'run_id')::uuid is distinct from p_run_id
     or p_attestation_payload->>'stage_code' is distinct from p_stage_code then
    raise exception 'PERSISTENCE_ATTESTATION_INVALID'
      using errcode = '23514';
  end if;

  if not exists (
    select 1 from public.orotitan_runs r
    join public.orotitan_run_stages s on s.run_id=r.run_id
    where r.run_id=p_run_id
      and r.current_stage=p_stage_code
      and r.run_status not in ('PUBLISHED','CANCELLED')
      and s.stage_code=p_stage_code
      and s.lifecycle_status <> 'COMPLETE'
  ) then
    raise exception 'PERSISTENCE_ATTESTATION_STAGE_NOT_ACTIVE'
      using errcode = '23514';
  end if;

  v_fingerprint := encode(
    extensions.digest(convert_to(p_attestation_payload::text,'UTF8'),'sha256'),
    'hex'
  );
  v_idempotency_key := 'persistence-attest:' ||
    p_attestation_payload->>'artifact_id' || ':' ||
    p_attestation_payload->>'version' || ':' ||
    v_fingerprint;

  v_retry := public.orotitan_existing_event(p_run_id,v_idempotency_key,v_fingerprint);
  if v_retry is not null then
    return (v_retry->>'event_id')::uuid;
  end if;

  v_event_id := public.orotitan_insert_event(
    p_run_id,p_stage_code,'PERSISTENCE_ATTESTED',
    v_idempotency_key,v_fingerprint,'SYSTEM',p_attestation_payload
  );
  return v_event_id;
end;
$$;

create or replace function public.orotitan_register_manifest_bundle(
  p_run_id uuid,
  p_stage_code text,
  p_manifest jsonb,
  p_manifest_registration jsonb,
  p_output_artifacts jsonb,
  p_edges jsonb
)
returns void
language plpgsql
set search_path = pg_catalog, public
as $$
declare
  v_stage public.orotitan_run_stages%rowtype;
  v_manifest_id uuid := (p_manifest->>'manifest_id')::uuid;
  v_manifest_version integer := (p_manifest_registration->>'version')::integer;
  v_manifest_kind text := p_manifest->>'manifest_kind';
  v_expected_authority_class text;
  v_expected_authority_state text;
  v_output jsonb;
  v_ref jsonb;
  v_match jsonb;
  v_edge jsonb;
  v_storage_ref jsonb;
  v_count integer;
begin
  select * into v_stage
  from public.orotitan_run_stages
  where run_id=p_run_id and stage_code=p_stage_code;
  if not found then raise exception 'STAGE_NOT_FOUND' using errcode='P0002'; end if;

  if v_manifest_kind='CHECKPOINT' then
    v_expected_authority_class := 'CHECKPOINT_STAGE_OUTPUT';
    v_expected_authority_state := 'CHECKPOINT';
  elsif v_manifest_kind='FINAL' then
    v_expected_authority_class := 'AUTHORITATIVE_STAGE_OUTPUT';
    v_expected_authority_state := 'AUTHORITATIVE';
  else
    raise exception 'MANIFEST_CONTRACT_MISMATCH: unsupported manifest kind'
      using errcode='23514';
  end if;

  if (p_manifest->>'run_id')::uuid is distinct from p_run_id
     or p_manifest->>'stage' is distinct from p_stage_code
     or (p_manifest->>'stage_revision')::integer is distinct from v_stage.stage_revision
     or p_manifest_registration->>'artifact_id' is distinct from v_manifest_id::text then
    raise exception 'MANIFEST_CONTRACT_MISMATCH: run/stage/revision/identity mismatch'
      using errcode='23514';
  end if;

  if p_manifest_registration->>'authority_class' is distinct from v_expected_authority_class
     or p_manifest_registration->>'authority_state' is distinct from v_expected_authority_state
     or coalesce(p_manifest_registration->>'artifact_status','SEALED') <> 'SEALED'
     or coalesce(p_manifest_registration->>'availability_state','AVAILABLE') <> 'AVAILABLE' then
    raise exception 'MANIFEST_CONTRACT_MISMATCH: manifest registration authority/status mismatch'
      using errcode='23514';
  end if;

  if coalesce(jsonb_typeof(p_output_artifacts),'null') <> 'array'
     or coalesce(jsonb_typeof(p_edges),'null') <> 'array'
     or coalesce(jsonb_typeof(p_manifest->'output_artifacts'),'null') <> 'array' then
    raise exception 'manifest bundle arrays are malformed' using errcode='22023';
  end if;

  if jsonb_array_length(p_output_artifacts) <> jsonb_array_length(p_manifest->'output_artifacts') then
    raise exception 'ARTIFACT_NOT_IN_MANIFEST: output artifact count mismatch'
      using errcode='23514';
  end if;

  if exists (
    select 1 from jsonb_array_elements(p_output_artifacts) x
    group by x->>'artifact_id',x->>'version' having count(*)>1
  ) then
    raise exception 'ARTIFACT_NOT_IN_MANIFEST: duplicate output artifact registration'
      using errcode='23514';
  end if;

  -- Manifest bytes + immutable locator authority are checked before any
  -- artifact/edge/state mutation. Semantic JSON must equal the submitted manifest.
  perform public.orotitan_validate_attested_bundle_object(
    p_run_id,p_stage_code,p_manifest_registration,p_manifest
  );

  -- Prevalidate every output so one bad object rejects the complete bundle.
  for v_ref in select value from jsonb_array_elements(p_manifest->'output_artifacts')
  loop
    if v_ref->>'authority_class' is distinct from v_expected_authority_class
       or coalesce(jsonb_typeof(v_ref->'storage_ref'),'null') <> 'object' then
      raise exception 'MANIFEST_CONTRACT_MISMATCH: output reference authority/storage binding invalid'
        using errcode='23514';
    end if;

    select value into v_match
    from jsonb_array_elements(p_output_artifacts)
    where value->>'artifact_id'=v_ref->>'artifact_id'
      and value->>'version'=v_ref->>'version';

    if not found
       or v_match->>'content_sha256' is distinct from v_ref->>'content_sha256'
       or v_match->>'artifact_type' is distinct from v_ref->>'artifact_type'
       or v_match->>'authority_class' is distinct from v_ref->>'authority_class'
       or v_match->>'media_type' is distinct from v_ref->>'media_type'
       or (v_match->>'size_bytes')::bigint is distinct from (v_ref->>'size_bytes')::bigint
       or v_match->>'authority_class' is distinct from v_expected_authority_class
       or v_match->>'authority_state' is distinct from v_expected_authority_state
       or coalesce(v_match->>'artifact_status','SEALED') <> 'SEALED'
       or coalesce(v_match->>'availability_state','AVAILABLE') <> 'AVAILABLE' then
      raise exception 'ARTIFACT_NOT_IN_MANIFEST: output artifact mismatch'
        using errcode='23514';
    end if;

    v_storage_ref := v_ref->'storage_ref';
    if v_storage_ref->>'backend' is distinct from v_match->>'storage_backend'
       or v_storage_ref->>'repository' is distinct from v_match->>'github_repository'
       or v_storage_ref->>'path' is distinct from v_match->>'github_path'
       or v_storage_ref->>'commit_sha' is distinct from v_match->>'github_commit_sha'
       or v_storage_ref->>'blob_sha' is distinct from v_match->>'github_blob_sha'
       or v_storage_ref->>'storage_uri' is distinct from v_match->>'storage_uri' then
      raise exception 'MANIFEST_BINDING_MISMATCH: output immutable locator differs from manifest storage_ref'
        using errcode='23514';
    end if;

    perform public.orotitan_validate_attested_bundle_object(
      p_run_id,p_stage_code,v_match,null
    );
  end loop;

  for v_output in select value from jsonb_array_elements(p_output_artifacts)
  loop
    select count(*) into v_count
    from jsonb_array_elements(p_manifest->'output_artifacts')
    where value->>'artifact_id'=v_output->>'artifact_id'
      and value->>'version'=v_output->>'version';
    if v_count <> 1 then
      raise exception 'ARTIFACT_NOT_IN_MANIFEST: extra or duplicate output artifact'
        using errcode='23514';
    end if;
  end loop;

  -- All persistence receipts and locator attestations have passed.
  perform public.orotitan_insert_artifact_registration(
    p_run_id,p_stage_code,p_manifest_registration,null,null
  );

  for v_ref in select value from jsonb_array_elements(p_manifest->'output_artifacts')
  loop
    select value into v_match
    from jsonb_array_elements(p_output_artifacts)
    where value->>'artifact_id'=v_ref->>'artifact_id'
      and value->>'version'=v_ref->>'version';

    perform public.orotitan_insert_artifact_registration(
      p_run_id,p_stage_code,v_match,v_manifest_id,v_manifest_version
    );
  end loop;

  for v_edge in select value from jsonb_array_elements(p_edges)
  loop
    insert into public.orotitan_artifact_edges(
      child_run_id,child_artifact_id,child_version,
      parent_run_id,parent_artifact_id,parent_version,relation_type
    ) values (
      coalesce((v_edge->>'child_run_id')::uuid,p_run_id),
      (v_edge->>'child_artifact_id')::uuid,
      (v_edge->>'child_version')::integer,
      (v_edge->>'parent_run_id')::uuid,
      (v_edge->>'parent_artifact_id')::uuid,
      (v_edge->>'parent_version')::integer,
      v_edge->>'relation_type'
    ) on conflict do nothing;
  end loop;
end;
$$;

revoke all on function public.orotitan_validate_attested_bundle_object(uuid,text,jsonb,jsonb)
  from public,anon,authenticated,service_role;
revoke all on function public.attest_orotitan_persistence_locator(uuid,text,jsonb)
  from public,anon,authenticated,service_role;
revoke all on function public.orotitan_register_manifest_bundle(uuid,text,jsonb,jsonb,jsonb,jsonb)
  from public,anon,authenticated,service_role;

commit;
